<a href="https://colab.research.google.com/github/Boggavarapudeepthi/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
print(numpy.__version__)

2.0.2


In [ ]:
import numpy as np
a=np.array([10,20,30])
print(a)

[10 20 30]


In [ ]:
#tri dimentional array
import numpy as np
a=np.array([[10,20],[30,40],[50,60]])
print(a)

[[10 20]
 [30 40]
 [50 60]]


In [ ]:
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [ ]:
a=np.array([[10,20],[30,40]])
print(a[0][1])

20


In [ ]:
a=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
